name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
sort-by: title
sort-direction: ascending
template: |
  $CHANGES
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '⚡️ Improvements'
    labels:
      - 'improvement'
      - 'refactor'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🤖 Dependencies'
    label: 'dependencies'
exclude-labels:
  - 'ignore'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
