service: abs
frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  architecture: x86_64
  runtime: go1.x
  memorySize: 128
  timeout: 10
  environment:
    slackToken: ${self:custom.environment.slackToken}
    channelId: ${self:custom.environment.channelId}
    botId: ${self:custom.environment.botId}
    DB_HOST: ${self:custom.environment.DB_HOST}
    DB_AUTH: ${self:custom.environment.DB_AUTH}
    DB_NAME: ${self:custom.environment.DB_Name}

custom:
  environment: ${file(secret.yml), file(secret.yml):default}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  abs:
    handler: bin/abs
    events:
      - http:
          path: /{proxy+}
          method: any
