service: abs
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: ap-northeast-2
  architecture: x86_64
  runtime: go1.x
  memorySize: 128
  timeout: 10
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_AUTH: ${env:DB_AUTH}
    DB_NAME: ${env:DB_NAME}
    GO_ENV: ${env:GO_ENV}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  abs:
    handler: bin/abs
    events:
      - http:
          path: /{proxy+}
          method: any
