service: abs
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: ap-northeast-2
  architecture: x86_64
  runtime: go1.x
  memorySize: 128
  timeout: 10
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_AUTH: ${env:DB_AUTH}
    DB_NAME: ${env:DB_NAME}
    GO_ENV: production

package:
  patterns:
    - '!**'
    - 'bin/**'

functions:
  abs:
    handler: bin/abs
    events:
      - http:
          path: /{proxy+}
          method: any
          cors:
            origin: 'https://jesh-hub.github.io'
          headers:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
            - X-Amzn-Trace-Id
          allowCredentials: false

