service: abs
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  region: ap-northeast-2
  architecture: x86_64
  runtime: go1.x
  memorySize: 128
  timeout: 10
  httpApi:
    cors:
      allowedOrigins:
        - '*'
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_AUTH: ${env:DB_AUTH}
    DB_NAME: ${env:DB_NAME}
    ALLOW_ORIGIN: ${env:ALLOW_ORIGIN}
    GO_ENV: production

package:
  patterns:
    - '!**'
    - 'bin/**'

functions:
  abs:
    name: abs-${sls:stage}
    handler: bin/abs
    events:
      - httpApi:
          path: /{proxy+}
          method: any
