name: Backend CI/CD

on:
  push:
    branches: [ master ]
    paths: [ "back-end/**", ".github/workflows/backend-cicd.yml" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: back-end
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: |
          npm i -g serverless
          npm ci

      - name: Create serverless secret file
        working-directory: ${{ env.working-directory }}
        run: touch secret.yml
        
      - name: Update serverless secret file
        uses: mikefarah/yq@v4.25.1
        with:
          cmd: slackToken=${{ secrets.SLACKTOKEN }} channelId=${{ secrets.CHANNELID }} botId=${{ secrets.BOTID }} yq -i '.slackToken = strenv(slackToken) | .channelId = strenv(channelId) | .botId = strenv(botId)' ${{ env.working-directory }}/secret.yml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
      - name: serverless deploy
        working-directory: ${{ env.working-directory }}
        run: |
          CHECK_SLS_CONFIG_CHANGED=`git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -i serverless.yml | wc -l`
          if [ $CHECK_SLS_CONFIG_CHANGED -gt 0 ]; then
            make deploy-all
          else
            make deploy
          fi
